### ISSUE TITLE
Possible fix to font issue

### ISSUE THREAD

**Issue by nickc5802** [freeterrybrown/freeterrybrown.github.io#1]
Try checking the capitalization of the folder where the font is stored. The folder is called *cardshark*, but in the code you said *CardShark*.

rather than
`@font-face {
   font-family: cardshark;
   src: url('fonts/CardShark/CardShark.ttf');
}`
do 
`@font-face {
   font-family: cardshark;
   src: url('fonts/cardshark/CardShark.ttf');
}`

**Comment by Jules3182** [comment]
It worked! Thank you nick!
